### ISSUE TITLE
Having Userscript-Plus enabled blocks loading of keep.google.com

### ISSUE THREAD

**Issue by johnny5wd** [magicoflolis/Userscript-Plus#53] opened 2024-08-24 10:37 UTC
Perceived Issue:
Having Userscript-Plus enabled blocks proper loading of keep.google.com

How to reproduce?
1) On Windows, start Google Chrome (see below for details)
2) empty any caches or buffers
3) Navigate to keep.google.com with Tampermonkey and Userscript-Plus enabled
4) Page does not finish loading its scripts and becomes unusable

How to temporarily resolve?
Can be resolved by adding keep.google.com to the exceptions, but then one won't be alerted to new scripts relevant to Google Keep.

Tested on 2024.08.24:
Windows 11 Pro 21H2 Build 22000.1936
Version 127.0.6533.122 (Official Build) (64-bit)

**Comment by magicoflolis** [comment] 2024-08-27 19:36
Fixed as of v6.7.0, this issue was caused by Trusted Types on Chrome. https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API

https://github.com/magicoflolis/Userscript-Plus/releases/tag/6.7.0

**Closed by magicoflolis** 2024-08-27 19:36 UTC
